INSERT INTO menu_items (name, description, price_per_item, image_url, category)
VALUES
  ('Burger1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Arcu ac tortor dignissim convallis aenean et.', 1000, 'https://media.istockphoto.com/photos/double-cheese-burger-picture-id945057664?k=20&m=945057664&s=612x612&w=0&h=XO55EntWLjms3G2DaVd20dxrTGbDXGjYr6xNSyBCfNE=', 'Burgers'),
  ('Burger2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Arcu ac tortor dignissim convallis aenean et.', 500, 'https://media.istockphoto.com/photos/double-cheese-burger-picture-id945057664?k=20&m=945057664&s=612x612&w=0&h=XO55EntWLjms3G2DaVd20dxrTGbDXGjYr6xNSyBCfNE=', 'Burgers'),
  ('Burger3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Arcu ac tortor dignissim convallis aenean et.', 1500, 'https://media.istockphoto.com/photos/double-cheese-burger-picture-id945057664?k=20&m=945057664&s=612x612&w=0&h=XO55EntWLjms3G2DaVd20dxrTGbDXGjYr6xNSyBCfNE=', 'Burgers'),
  ('Burger4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Arcu ac tortor dignissim convallis aenean et.', 1500, 'https://media.istockphoto.com/photos/double-cheese-burger-picture-id945057664?k=20&m=945057664&s=612x612&w=0&h=XO55EntWLjms3G2DaVd20dxrTGbDXGjYr6xNSyBCfNE=', 'Burgers'),
  ('Burger5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Arcu ac tortor dignissim convallis aenean et.', 1500, 'https://media.istockphoto.com/photos/double-cheese-burger-picture-id945057664?k=20&m=945057664&s=612x612&w=0&h=XO55EntWLjms3G2DaVd20dxrTGbDXGjYr6xNSyBCfNE=', 'Burgers'),
  ('Fries1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 799, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZnJpZXN8ZW58MHx8MHx8&w=1000&q=80', 'Sides'),
  ('Fries2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 499, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZnJpZXN8ZW58MHx8MHx8&w=1000&q=80', 'Sides'),
  ('PepsiBoujie', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2000, 'https://thumbs.dreamstime.com/b/pepsi-can-isolated-cold-soft-caffeine-white-63395552.jpg', 'Drinks'),
  ('Pepsi1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 150, 'https://thumbs.dreamstime.com/b/pepsi-can-isolated-cold-soft-caffeine-white-63395552.jpg', 'Drinks'),
  ('Pepsi2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 200, 'https://thumbs.dreamstime.com/b/pepsi-can-isolated-cold-soft-caffeine-white-63395552.jpg', 'Drinks');
